version: 0.2
env:
  shell: bash
  variables:
    EXIT_CODE: 0
    VALIDATION_FUNCTION_EXIT_CODE: 0
    ERROR_MESSAGE: ""
phases:
  pre_build:
    commands:
      - echo "Installing dependencies"
      - apt-get install python3-pip -y -q
      - pip install -q boto3 botocore
      - echo 'The source artifact location is:' $CODEBUILD_SOURCE_VERSION
      - echo 'The extracted source artifact bucket name is:' $CODEBUILD_SOURCE_VERSION | awk -F'/' '{print $1}' | awk -F':::' '{print $2}'
      - export ARTIFACT_S3_BUCKET_NAME=$(echo "$CODEBUILD_SOURCE_VERSION" | awk -F'/' '{print $1}' | awk -F':::' '{print $2}')
  build:
    commands:
      - ls -lah
      - echo "Starting validation phase"
      - python3 src/validation/syntax-validator.py || VALIDATION_FUNCTION_EXIT_CODE=$?
      - |
        if [ $VALIDATION_FUNCTION_EXIT_CODE -ne 0 ]; then 
        ERROR_MESSAGE="[ERROR]Validation function (syntax_validator.py) failed with exit code $VALIDATION_FUNCTION_EXIT_CODE :( Please see function logs above or in CloudWatch for details"
        EXIT_CODE=$VALIDATION_FUNCTION_EXIT_CODE
        fi
      - echo 'Exiting build with final exit code:' $EXIT_CODE
      - exit $EXIT_CODE
  post_build:
    commands:
      - echo "Validation Action complete"