version: 0.2
env:
  git-credential-helper: yes
phases:
  build:
    commands:
      - echo "Create CloudFormation Parameter Files."
      - pwd
      - sudo apt install -y jq
      - jq "del(.Parameters.OrganizationId, .Parameters.ICKMSAdminArn)" identity-center-stacks-parameters.json > ic-automation-parameters.json
      - jq "del(.Parameters.IdentityStoreId, .Parameters.SNSEmailEndpointSubscription, .Parameters.ICInstanceARN)" identity-center-stacks-parameters.json > ic-s3-parameters.json
      - cat ic-automation-parameters.json
      - cat ic-s3-parameters.json
      - echo "Process is completed"

artifacts:
  files:
    - '**/*'
