version: 0.2
env:
  git-credential-helper: yes
phases:
  pre_build:
    commands:
      - export DEBIAN_FRONTEND=noninteractive
      - apt update
      - apt-get install python3-pip -y -q
      - apt-get install jq git ruby-rubygems   -y -q
      - pip3 install cfn-lint --quiet              
      - gem install cfn-nag
      - which cfn_nag_scan
      - echo 'The source artifact location is:' $CODEBUILD_SOURCE_VERSION
      - echo 'The extracted source artifact bucket name is:' $CODEBUILD_SOURCE_VERSION | awk -F'/' '{print $1}' | awk -F':::' '{print $2}'
      - export ARTIFACT_S3_BUCKET_NAME=$(echo "$CODEBUILD_SOURCE_VERSION" | awk -F'/' '{print $1}' | awk -F':::' '{print $2}')
  build:
    commands:
      - set -eux
      - echo "Create CloudFormation Parameter Files."
      - jq --arg artifact_bucket "$ARTIFACT_S3_BUCKET_NAME" '.Parameters.ArtifactBucketName = $artifact_bucket' identity-center-stacks-parameters.json > ic-automation-parameters.json
      - jq "del(.Parameters.OrganizationId, .Parameters.ICKMSAdminArn, .Parameters.createICKMSAdminRole, .Parameters.createICAdminRole, .Parameters.createS3KmsKey, .Parameters.S3KmsArn)" ic-automation-parameters.json > temp.json && mv temp.json ic-automation-parameters.json
      - jq "del(.Parameters.IdentityStoreId, .Parameters.SNSEmailEndpointSubscription, .Parameters.ICInstanceARN, .Parameters.OrgManagementAccount, .Parameters.AdminDelegated, .Parameters.ControlTowerEnabled)" identity-center-stacks-parameters.json > ic-s3-parameters.json
      - cat ic-automation-parameters.json
      - cat ic-s3-parameters.json
      - echo "Parameter Process is done."
      - ls -lah
      # CFN Template Linting and Security Scans 
      - echo "Start scanning CloudFormation templates using cfn-nag Tool......."
      - cfn_nag_scan --input-path templates/codepipeline-stack.template
      - cfn_nag_scan --input-path templates/delegate-admin/IC-Delegate-Admin.template
      - cfn_nag_scan --input-path templates/identity-center-s3-bucket.template
      - cfn_nag_scan --input-path templates/identity-center-automation.template
      - cfn_nag_scan --input-path templates/management-account-org-events-forwarder.template

artifacts:
  files:
    - '**/*'