version: 0.2

env:
  git-credential-helper: yes
phases:
  build:
    commands:
      - echo "Sync mapping files to S3 secure bucket"
      - pwd
      - ls -lah
      - git log | head -10
      - aws s3 sync --delete  sso-mapping-info/ s3://$S3_BUCKET_NAME/
      - aws s3api list-objects-v2 --bucket $S3_BUCKET_NAME
      - echo "Sync done."