version: 0.2

env:
  git-credential-helper: yes
phases:
  build:
    commands:
      - echo "Sync mapping files to S3 bucket"
      - pwd
      - ls -lah
      - git log | head -10
      - aws s3 sync --delete  mapping_example/ s3://replace_with_your_sso_s3_bucketname/
      - aws s3api list-objects-v2 --bucket replace_with_your_sso_s3_bucketname
      - echo "Done"